name: critical_x_quiz
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  percent_indicator: ^2.1.8
  google_fonts: ^1.1.1
  flutter_svg: ^0.19.0
  flutter_responsive_screen: ^1.0.0
  smooth_page_indicator: ^0.2.0
  page_transition: ^1.1.7+3

  bottom_navy_bar: ^5.6.0

  #firebase
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4

  firebase_storage: ^5.2.0
  firebase_core: ^0.5.3
  #flutter micro framework
  get: ^3.22.2
  get_storage: ^1.3.2

  #toast
  toast: ^0.1.5

  #validator
  validators: ^2.0.1
  csv: ^4.1.0
  file_picker: ^2.1.0

  flutter_native_image: ^0.0.5
  image_picker: ^0.6.7+14
  camera: ^0.5.8+17
  shape_of_view: ^1.0.2
  uuid: ^2.2.2
  intl: ^0.16.1
  flutter_easyloading: ^2.2.1








dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

    - images/cardiac.svg
    - images/test.svg



  #   - images/a_dot_ham.jpeg

    - assets/svg/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FlutterImageAdd
      fonts:
        - asset: fonts/FlutterImageAdd.ttf
    - family: FlutterNevBarIcons
      fonts:
        - asset: fonts/FlutterNevBarIcons.ttf
    - family: CorrectIcon
      fonts:
        - asset: fonts/CorrectIcon.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
