/// Flutter icons FlutterImageAdd
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterImageAdd
///      fonts:
///       - asset: fonts/FlutterImageAdd.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FlutterImageAdd {
  FlutterImageAdd._();

  static const _kFontFam = 'FlutterImageAdd';
  static const _kFontPkg = null;

  static const IconData image_add = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
